# Generated by Django 4.2.4 on 2023-08-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='owner_slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
