# Generated by Django 4.2.4 on 2023-08-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_owner_owner_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owner_slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
