# Generated by Django 4.2.4 on 2023-09-01 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentpayment',
            name='is_successful',
            field=models.BooleanField(default=False),
        ),
    ]
