# Generated by Django 4.2.4 on 2023-08-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_category_options_listings_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
