# Generated by Django 4.2.4 on 2023-08-23 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listings_is_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='listings',
            name='slug',
        ),
    ]
